/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rasy;

import java.sql.*;
import rasy.login_page;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class forgot_pass extends javax.swing.JFrame {
    Connection con = null;
    Statement stmt = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;

    /**
     * Creates new form forgot_pass
     */
    public forgot_pass() {
        initComponents();
        jLabel3.setVisible(false);
        jTextNewPass.setVisible(false);
        jBConfirm.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jCBType = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jTextUser = new javax.swing.JTextField();
        jTextQuestion = new javax.swing.JTextField();
        jBLogin = new javax.swing.JButton();
        jBReset = new javax.swing.JButton();
        jBBack = new javax.swing.JButton();
        jCBQuestion = new javax.swing.JComboBox();
        jBConfirm = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextNewPass = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1339, 779));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setPreferredSize(new java.awt.Dimension(187, 124));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Vladimir Script", 1, 58)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rasy/Logo_bg.jpg"))); // NOI18N
        jLabel1.setText("            RASY Transport Company              ");

        jPanel3.setPreferredSize(new java.awt.Dimension(0, 500));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1352, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1352, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        jCBType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCBType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select type of User", "Admin", "Manager", "User" }));
        jCBType.setPreferredSize(new java.awt.Dimension(135, 24));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("User ID                              :");
        jLabel2.setPreferredSize(new java.awt.Dimension(170, 24));

        jTextUser.setPreferredSize(new java.awt.Dimension(200, 24));
        jTextUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUserActionPerformed(evt);
            }
        });

        jTextQuestion.setPreferredSize(new java.awt.Dimension(400, 24));

        jBLogin.setBackground(new java.awt.Color(204, 204, 255));
        jBLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBLogin.setText("Submit");
        jBLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBLogin.setPreferredSize(new java.awt.Dimension(78, 28));
        jBLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLoginActionPerformed(evt);
            }
        });

        jBReset.setBackground(new java.awt.Color(204, 204, 255));
        jBReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBReset.setText("Reset");
        jBReset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBReset.setPreferredSize(new java.awt.Dimension(78, 28));
        jBReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBResetActionPerformed(evt);
            }
        });

        jBBack.setBackground(new java.awt.Color(204, 204, 255));
        jBBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBBack.setText("Back");
        jBBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBBack.setPreferredSize(new java.awt.Dimension(78, 28));
        jBBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBackActionPerformed(evt);
            }
        });

        jCBQuestion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCBQuestion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Question", "My best friend name?", "My first school name?", "MID (in case of manager)" }));
        jCBQuestion.setMinimumSize(new java.awt.Dimension(64, 24));
        jCBQuestion.setPreferredSize(new java.awt.Dimension(64, 24));
        jCBQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBQuestionActionPerformed(evt);
            }
        });

        jBConfirm.setBackground(new java.awt.Color(204, 204, 255));
        jBConfirm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBConfirm.setText("Confirm");
        jBConfirm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBConfirm.setPreferredSize(new java.awt.Dimension(78, 28));
        jBConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfirmActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("New Password                    :");
        jLabel3.setPreferredSize(new java.awt.Dimension(170, 24));

        jTextNewPass.setPreferredSize(new java.awt.Dimension(400, 24));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1356, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCBType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCBQuestion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBReset, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jBBack, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(308, 308, 308))
                    .addComponent(jTextNewPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(378, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(jCBType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jBConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUserActionPerformed

    private void jBLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLoginActionPerformed
        if(jCBType.getSelectedItem()=="User"){
            String typeuser = jTextUser.getText();
            String typequestion = (String) jCBQuestion.getSelectedItem();
            String typeanswer = jTextQuestion.getText();
            String user, question, answer;
            try{
                Class.forName("java.sql.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/rasy","root","90897");
                pstmt = con.prepareStatement("Select * from user where user_name = '"+jTextUser.getText()+"';");
                rs = pstmt.executeQuery();
                if(rs.next()){
                    user = rs.getString("user_name");
                    question = rs.getString("question");
                    answer = rs.getString("answer");

                    if(user.equals(typeuser) && question.equals(typequestion) && answer.equals(typeanswer)){
                        jLabel3.setVisible(true);
                        jTextNewPass.setVisible(true);
                        jBConfirm.setVisible(true);
                        JOptionPane.showMessageDialog(null, "Enter new password");
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Invaid UserId or Answer");
                    }
                }
            }

            catch(Exception e){
                JOptionPane.showMessageDialog(null, "Something went wrong, Please try again later...");
            }
        }
        
        else if(jCBType.getSelectedItem()=="Manager"){
            
            String typeuser = jTextUser.getText();
            String typequestion = (String) jCBQuestion.getSelectedItem();
            String typeanswer = jTextQuestion.getText();
            String user, question, answer;
            try{
                Class.forName("java.sql.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/rasy","root","90897");
                pstmt = con.prepareStatement("Select * from manager where user_name = '"+jTextUser.getText()+"';");
                rs = pstmt.executeQuery();
                if(rs.next()){
                    user = rs.getString("user_name");
                    question = rs.getString("question");
                    answer = rs.getString("password");

                    if(user.equals(typeuser) && answer.equals(typeanswer)){
                        jLabel3.setVisible(true);
                        jTextNewPass.setVisible(true);
                        jBConfirm.setVisible(true);
                        JOptionPane.showMessageDialog(null, "Enter new password");
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Invaid UserId or Answer");
                    }
                }
            }

            catch(Exception e){
                JOptionPane.showMessageDialog(null, "Something went wrong, Please try again later...");
            }
        }
    }//GEN-LAST:event_jBLoginActionPerformed

    private void jBResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBResetActionPerformed
        jTextUser.setText(null);
        jTextQuestion.setText(null);
    }//GEN-LAST:event_jBResetActionPerformed

    private void jBBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBackActionPerformed
        login_page inf = new login_page();
        inf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBBackActionPerformed

    private void jCBQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBQuestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBQuestionActionPerformed

    private void jBConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmActionPerformed
        if(jCBType.getSelectedItem()=="User"){
            try{
                    Class.forName("java.sql.Driver");
                    con = DriverManager.getConnection("jdbc:mysql://localhost/rasy","root","90897");
                    pstmt = con.prepareStatement("Update user set password = '"+jTextNewPass.getText()+"' where user_name = '"+jTextUser.getText()+"';");
                    int i = pstmt.executeUpdate();
                    
                    if(i>0){
                        JOptionPane.showMessageDialog(null, "Update Successfull");
                        login_page info = new login_page();
                        info.setVisible(true);
                        this.setVisible(false);
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Something went wrong, Please try again later...");
                    }
                }

            catch(Exception e){
                JOptionPane.showMessageDialog(null, "Something went wrong, Please try again later...");
            }    
        }
        
        else if(jCBType.getSelectedItem()=="Manager"){
            try{
                    Class.forName("java.sql.Driver");
                    con = DriverManager.getConnection("jdbc:mysql://localhost/rasy","root","90897");
                    pstmt = con.prepareStatement("Update manager set password = '"+jTextNewPass.getText()+"' where user_name = '"+jTextUser.getText()+"';");
                    int i = pstmt.executeUpdate();
                    
                    if(i>0){
                        JOptionPane.showMessageDialog(null, "Update Successfull");
                        login_page info = new login_page();
                        info.setVisible(true);
                        this.setVisible(false);
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Something went wrong, Please try again later...");
                    }
                }

            catch(Exception e){
                JOptionPane.showMessageDialog(null, "Something went wrong, Please try again later...");
            }    
        }
        
        
    }//GEN-LAST:event_jBConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgot_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgot_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgot_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgot_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgot_pass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBack;
    private javax.swing.JButton jBConfirm;
    private javax.swing.JButton jBLogin;
    private javax.swing.JButton jBReset;
    private javax.swing.JComboBox jCBQuestion;
    private javax.swing.JComboBox jCBType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextNewPass;
    private javax.swing.JTextField jTextQuestion;
    private javax.swing.JTextField jTextUser;
    // End of variables declaration//GEN-END:variables
}
