/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rasy;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class user_dash extends javax.swing.JFrame {
    Connection con = null;
    Statement stmt = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    /**
     * Creates new form user_dash
     */
    public user_dash() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTMob = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jCBType = new javax.swing.JComboBox();
        jCBFrom = new javax.swing.JComboBox();
        jCBTo = new javax.swing.JComboBox();
        jTWeight = new javax.swing.JTextField();
        jLId = new javax.swing.JLabel();
        jBCalc = new javax.swing.JButton();
        jBReset = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLTc = new javax.swing.JLabel();
        jBConfirm = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTId = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLMob = new javax.swing.JLabel();
        jBCalc1 = new javax.swing.JButton();
        jBReset1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLName = new javax.swing.JLabel();
        jLFrom = new javax.swing.JLabel();
        jLTo = new javax.swing.JLabel();
        jLTotal = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLStatus = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1339, 779));
        setMinimumSize(new java.awt.Dimension(1339, 779));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setMaximumSize(new java.awt.Dimension(1339, 779));
        jPanel1.setMinimumSize(new java.awt.Dimension(1339, 779));
        jPanel1.setPreferredSize(new java.awt.Dimension(1339, 779));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setPreferredSize(new java.awt.Dimension(187, 124));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Vladimir Script", 1, 58)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rasy/Logo_bg.jpg"))); // NOI18N
        jLabel1.setText("            RASY Transport Company              ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 255));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1311, 600));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(1311, 600));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1311, 600));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setMaximumSize(new java.awt.Dimension(674, 585));
        jPanel4.setMinimumSize(new java.awt.Dimension(674, 585));

        jLabel2.setIcon(new javax.swing.ImageIcon("F:\\5th sem Project\\Dash.jpg")); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(674, 585));
        jLabel2.setMinimumSize(new java.awt.Dimension(674, 585));
        jLabel2.setPreferredSize(new java.awt.Dimension(674, 585));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 557));

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 34)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Moving your products across all borders");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("<html> \n<p>\nWelcome to our Transport Comapny. We are assuring you the safest and fastest delivery of your goods and services. You can find all the information regarding our company and the services we are providing. You can contact us also if you want to get your truck installed in our company. You can easily contact us by using the Contact us page or by using below mentioned mobile numbers.\n </p> \n</html>\n\n\n");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel4.setAlignmentX(5.0F);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Contact Us : 9466447220");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(681, 0, -1, -1));

        jTabbedPane1.addTab("Home", jPanel3);

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Name                       :");
        jLabel6.setPreferredSize(new java.awt.Dimension(43, 24));
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 97, 138, -1));

        jTName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTName.setMaximumSize(new java.awt.Dimension(467, 24));
        jTName.setMinimumSize(new java.awt.Dimension(467, 24));
        jTName.setPreferredSize(new java.awt.Dimension(467, 24));
        jPanel6.add(jTName, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 97, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Mobile Number         :");
        jLabel7.setPreferredSize(new java.awt.Dimension(43, 24));
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 139, 138, -1));

        jTMob.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTMob.setMaximumSize(new java.awt.Dimension(467, 24));
        jTMob.setMinimumSize(new java.awt.Dimension(467, 24));
        jTMob.setPreferredSize(new java.awt.Dimension(467, 24));
        jPanel6.add(jTMob, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Type of Goods         :");
        jLabel8.setPreferredSize(new java.awt.Dimension(43, 24));
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 182, 138, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("From                       :");
        jLabel9.setPreferredSize(new java.awt.Dimension(43, 24));
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 224, 138, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("To                           :");
        jLabel10.setPreferredSize(new java.awt.Dimension(43, 24));
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 266, 138, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Weight (in Grams)   :");
        jLabel11.setPreferredSize(new java.awt.Dimension(43, 24));
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 308, 138, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Total Cost (in Rs)    : ");
        jLabel12.setPreferredSize(new java.awt.Dimension(43, 24));
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 409, 138, -1));

        jCBType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCBType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Electronic", "Paper", "Food/Preservatives", "Clothes" }));
        jCBType.setMaximumSize(new java.awt.Dimension(467, 24));
        jCBType.setMinimumSize(new java.awt.Dimension(467, 24));
        jCBType.setPreferredSize(new java.awt.Dimension(467, 24));
        jPanel6.add(jCBType, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 182, -1, -1));

        jCBFrom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCBFrom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Delhi", "Panipat" }));
        jCBFrom.setMaximumSize(new java.awt.Dimension(467, 24));
        jCBFrom.setMinimumSize(new java.awt.Dimension(467, 24));
        jCBFrom.setPreferredSize(new java.awt.Dimension(467, 24));
        jPanel6.add(jCBFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 224, -1, -1));

        jCBTo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCBTo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Delhi", "Panipat" }));
        jCBTo.setPreferredSize(new java.awt.Dimension(467, 24));
        jPanel6.add(jCBTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 266, -1, -1));

        jTWeight.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTWeight.setMaximumSize(new java.awt.Dimension(467, 24));
        jTWeight.setMinimumSize(new java.awt.Dimension(467, 24));
        jTWeight.setPreferredSize(new java.awt.Dimension(467, 24));
        jPanel6.add(jTWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 308, -1, -1));

        jLId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLId.setMaximumSize(new java.awt.Dimension(467, 24));
        jLId.setMinimumSize(new java.awt.Dimension(467, 24));
        jLId.setPreferredSize(new java.awt.Dimension(467, 24));
        jPanel6.add(jLId, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 505, -1, -1));

        jBCalc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBCalc.setText("Calculate Cost");
        jBCalc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBCalc.setPreferredSize(new java.awt.Dimension(89, 24));
        jBCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCalcActionPerformed(evt);
            }
        });
        jPanel6.add(jBCalc, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 359, 212, -1));

        jBReset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBReset.setText("Reset");
        jBReset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBReset.setPreferredSize(new java.awt.Dimension(37, 24));
        jBReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBResetActionPerformed(evt);
            }
        });
        jPanel6.add(jBReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 360, 212, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Unique Id                 : ");
        jLabel14.setPreferredSize(new java.awt.Dimension(43, 24));
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 505, 138, -1));

        jLTc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLTc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLTc.setMaximumSize(new java.awt.Dimension(467, 24));
        jLTc.setMinimumSize(new java.awt.Dimension(467, 24));
        jLTc.setPreferredSize(new java.awt.Dimension(467, 24));
        jPanel6.add(jLTc, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 409, -1, -1));

        jBConfirm.setBackground(new java.awt.Color(0, 153, 0));
        jBConfirm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBConfirm.setForeground(new java.awt.Color(255, 255, 255));
        jBConfirm.setText("Confirm Pick Up");
        jBConfirm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBConfirm.setMaximumSize(new java.awt.Dimension(467, 24));
        jBConfirm.setMinimumSize(new java.awt.Dimension(467, 24));
        jBConfirm.setPreferredSize(new java.awt.Dimension(467, 24));
        jBConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfirmActionPerformed(evt);
            }
        });
        jPanel6.add(jBConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 451, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1213, 530, 80, -1));

        jTabbedPane1.addTab("Pick Up", jPanel6);

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));

        jPanel9.setBackground(new java.awt.Color(204, 204, 255));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Name                       :");
        jLabel13.setPreferredSize(new java.awt.Dimension(43, 24));

        jTId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTId.setPreferredSize(new java.awt.Dimension(69, 24));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Mobile Number         :");
        jLabel15.setPreferredSize(new java.awt.Dimension(43, 24));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("From                       :");
        jLabel17.setPreferredSize(new java.awt.Dimension(43, 24));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("To                           :");
        jLabel18.setPreferredSize(new java.awt.Dimension(43, 24));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Total Cost (in Rs)    : ");
        jLabel20.setPreferredSize(new java.awt.Dimension(43, 24));

        jLMob.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLMob.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLMob.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLMob.setPreferredSize(new java.awt.Dimension(43, 24));

        jBCalc1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBCalc1.setText("Check");
        jBCalc1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBCalc1.setPreferredSize(new java.awt.Dimension(89, 24));
        jBCalc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCalc1ActionPerformed(evt);
            }
        });

        jBReset1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBReset1.setText("Reset");
        jBReset1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBReset1.setPreferredSize(new java.awt.Dimension(37, 24));
        jBReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReset1ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Unique Id                 : ");
        jLabel21.setPreferredSize(new java.awt.Dimension(43, 24));

        jLName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLName.setPreferredSize(new java.awt.Dimension(43, 24));

        jLFrom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLFrom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLFrom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLFrom.setPreferredSize(new java.awt.Dimension(43, 24));

        jLTo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLTo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLTo.setPreferredSize(new java.awt.Dimension(43, 24));

        jLTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLTotal.setPreferredSize(new java.awt.Dimension(43, 24));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Status                    :");
        jLabel22.setPreferredSize(new java.awt.Dimension(43, 24));

        jLStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLStatus.setPreferredSize(new java.awt.Dimension(43, 24));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(jLStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(jTId, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(87, 87, 87)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLMob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(jBCalc1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBReset1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 290, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jTId, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLMob, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLTo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCalc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBReset1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Delivery Status", jPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1335, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1335, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReset1ActionPerformed
        jTId.setText(null);
        jLName.setText(null);
        jLMob.setText(null);
        jLFrom.setText(null);
        jLTo.setText(null);
        jLTotal.setText(null);
        jLStatus.setText(null);
    }//GEN-LAST:event_jBReset1ActionPerformed

    private void jBCalc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCalc1ActionPerformed

        String id = jTId.getText();
        try{
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/rasy","root","90897");
            pstmt = con.prepareStatement("Select * from delivery where id = '"+jTId.getText()+"';");
            rs = pstmt.executeQuery();
            if(rs.next()){
                jLName.setText(rs.getString("name"));
                jLMob.setText(rs.getString("mobile"));
                jLFrom.setText(rs.getString("fr_om"));
                jLTo.setText(rs.getString("t_o"));
                jLTotal.setText(rs.getString("total"));
                jLStatus.setText(rs.getString("status"));
            }
            else{
                JOptionPane.showMessageDialog(null, "Invaid Order Id");
            }
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong, Please try again later...");
        }
    }//GEN-LAST:event_jBCalc1ActionPerformed

    private void jBConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmActionPerformed
        try{
            int id = (int) (Math.random()*3999);
            jLId.setText(""+id);
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/rasy","root","90897");
            pstmt = con.prepareStatement("insert into delivery values('"+jTName.getText()+"','"+jTMob.getText()+"','"+jCBType.getSelectedItem()+"','"+jCBFrom.getSelectedItem()+"','"+jCBTo.getSelectedItem()+"','"+jTWeight.getText()+"','"+jLTc.getText()+"','"+jLId.getText()+"','running');");
            int i = pstmt.executeUpdate();
            if(i>0){
                JOptionPane.showMessageDialog(null,"Order Placed Successfully, Your id for order : "+id);
            }
            else{
                JOptionPane.showMessageDialog(null,"Something Went Wrong, Please try agian later...");
            }
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jBConfirmActionPerformed

    private void jBResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBResetActionPerformed
        jTName.setText(null);
        jTMob.setText(null);
        jTWeight.setText(null);
        jLTc.setText(null);
        jLId.setText(null);
    }//GEN-LAST:event_jBResetActionPerformed

    private void jBCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCalcActionPerformed
        double ew = 0.1;
        double pw = 0.05;
        double fw = 0.07;
        double cw = 0.1;
        String type = (String)jCBType.getSelectedItem();
        String from = (String)jCBFrom.getSelectedItem();
        String to = (String)jCBTo.getSelectedItem();
        double weight = Double.parseDouble(jTWeight.getText());
        double total = 1;

        if("Electronic".equals(type)){
            total = (weight*ew)*2;
        }
        else if("Paper".equals(type)){
            total = (weight*pw)*2;
        }
        else if("Food/Preservatives".equals(type)){
            total = (weight*fw)*2;
        }
        else if("Clothes".equals(type)){
            total = (weight*cw)*2;
        }

        jLTc.setText("Rs "+total);

    }//GEN-LAST:event_jBCalcActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_dash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCalc;
    private javax.swing.JButton jBCalc1;
    private javax.swing.JButton jBConfirm;
    private javax.swing.JButton jBReset;
    private javax.swing.JButton jBReset1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jCBFrom;
    private javax.swing.JComboBox jCBTo;
    private javax.swing.JComboBox jCBType;
    private javax.swing.JLabel jLFrom;
    private javax.swing.JLabel jLId;
    private javax.swing.JLabel jLMob;
    private javax.swing.JLabel jLName;
    private javax.swing.JLabel jLStatus;
    private javax.swing.JLabel jLTc;
    private javax.swing.JLabel jLTo;
    private javax.swing.JLabel jLTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTId;
    private javax.swing.JTextField jTMob;
    private javax.swing.JTextField jTName;
    private javax.swing.JTextField jTWeight;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
